// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA55LXAXdmh-HTYqnUhTNklXxB6FhjqSZY',
    appId: '1:746413839062:web:b0f6ecf0a0da7850d6af77',
    messagingSenderId: '746413839062',
    projectId: 'crime-reporting-system-affc5',
    authDomain: 'crime-reporting-system-affc5.firebaseapp.com',
    storageBucket: 'crime-reporting-system-affc5.appspot.com',
    measurementId: 'G-VWZDSPW9VV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAxKJWo8MIfLlrqQ4NePAPN_47xmuQPBQQ',
    appId: '1:746413839062:android:ddcae141aab726add6af77',
    messagingSenderId: '746413839062',
    projectId: 'crime-reporting-system-affc5',
    storageBucket: 'crime-reporting-system-affc5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyClPYW2wXEFk94Q7h4TR_qx-dIeVnAAL2U',
    appId: '1:746413839062:ios:679bfa3b5164aa74d6af77',
    messagingSenderId: '746413839062',
    projectId: 'crime-reporting-system-affc5',
    storageBucket: 'crime-reporting-system-affc5.appspot.com',
    iosBundleId: 'com.example.adminportalcrimereportingsystem',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyClPYW2wXEFk94Q7h4TR_qx-dIeVnAAL2U',
    appId: '1:746413839062:ios:a67954efca083fead6af77',
    messagingSenderId: '746413839062',
    projectId: 'crime-reporting-system-affc5',
    storageBucket: 'crime-reporting-system-affc5.appspot.com',
    iosBundleId: 'com.example.adminportalcrimereportingsystem.RunnerTests',
  );
}
